# Site settings
baseurl: ""
url: "https://pretorh.github.io"
title: Hendri Pretorius
description: >
    Collection of experiments, findings, random scripts and more.

    Generally things I find interisting.
twitter_username: pretorh
github_username:  pretorh

# Build settings
markdown: kramdown
